# permissions for end users to view structures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: structure-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes
    app.kubernetes.io/part-of: kubernetes
    app.kubernetes.io/managed-by: kustomize
  name: structure-viewer-role
rules:
- apiGroups:
  - contractor.t3kton.com
  resources:
  - structures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - contractor.t3kton.com
  resources:
  - structures/status
  verbs:
  - get
