# This rule is not used by the project kubernetes itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the contractor.t3kton.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes
    app.kubernetes.io/managed-by: kustomize
  name: structure-editor-role
rules:
- apiGroups:
  - contractor.t3kton.com
  resources:
  - structures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - contractor.t3kton.com
  resources:
  - structures/status
  verbs:
  - get
