# This rule is not used by the project kubernetes itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over contractor.t3kton.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes
    app.kubernetes.io/managed-by: kustomize
  name: structure-admin-role
rules:
- apiGroups:
  - contractor.t3kton.com
  resources:
  - structures
  verbs:
  - '*'
- apiGroups:
  - contractor.t3kton.com
  resources:
  - structures/status
  verbs:
  - get
