apiVersion: contractor.t3kton.com/v1
kind: Structure
metadata:
  labels:
    app.kubernetes.io/name: structure
    app.kubernetes.io/instance: structure-sample
    app.kubernetes.io/part-of: kubernetes
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes
  name: structure-sample
spec:
  id: 3
  state: built
  blueprint: test-structure-base
  configurationValues:
    bmc_version: "2.3"
    bios_version: "4.5"
    some_key: some_value
    some_number: 5
    a_list: [5, 2, "asdf"]
    a_map: 
      key1: value1
      key2: 2
      key3: [1, 2, "sdf"]

  
